fix: hopefully setting correct folder name in github action script

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -1,27 +1,50 @@
-FROM node:18-alpine AS frontend-builder
-WORKDIR /frontend
+FROM node:18-alpine AS base
+
+FROM base AS deps
+
+RUN apk add --no-cache libc6-compat
+WORKDIR /app
+
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+FROM base AS builder
+WORKDIR /app
+
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
-RUN yarn install && yarn build
-RUN yarn install --production
 
-FROM node:20-bookworm-slim AS final-frontend
+RUN yarn build
 
-RUN useradd --uid 10000 --create-home runner
-USER 10000
 
-RUN mkdir -p /home/runner/.cache/yarn && \
-    mkdir -p /home/runner/.yarn
-
-ENV NODE_ENV=production
-ENV PRODUCTION=true
+FROM base AS runner
 
 WORKDIR /app
-COPY --from=frontend-builder /frontend/.next /app/.next
-COPY --from=frontend-builder /frontend/public /app/public
-COPY --from=frontend-builder /frontend/package.json /app/package.json
-COPY --from=frontend-builder /frontend/yarn.lock /app/yarn.lock
-COPY --from=frontend-builder /frontend/node_modules /app/node_modules
+
+ENV NODE_ENV=production
+
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 runner
+
+COPY --from=builder /app/public ./public
+
+# Set the correct permission for prerender cache
+RUN mkdir .next
+RUN chown runner:nodejs .next
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=runner:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=runner:nodejs /app/.next/static ./.next/static
+
+USER runner
 
 EXPOSE 3000
+ENV PORT=3000
 
-CMD ["yarn", "start", "--port", "3000"]
+CMD ["node", "server.js"]
